import com.derppening.derplib.dependency.`jetbrains-annotations`
import com.derppening.derplib.dependency.`junit-jupiter`
import com.derppening.derplib.dependency.`junit-platform`

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1.1/userguide/building_java_projects.html
 */

plugins {
    kotlin("jvm")
    `java-library`
    id("com.github.johnrengelman.shadow")
}

version = "0.1.0"

dependencies {
    compileOnly(`jetbrains-annotations`())

    // JUnit 5 stuff
    // TODO: Move these into a module or ext property
    testImplementation(`junit-jupiter`())
    testImplementation(`junit-platform`("runner"))
    testRuntimeOnly(`junit-platform`("console"))
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("1.9.0")
        }
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}
